### ISSUE TITLE
Website not working

### ISSUE THREAD

**Issue by SahilJindal1** [gveres/donateacry-corpus#6]
Hi @gveres ,

The website http://donateacry.com/ is not working. Kindly update this website. Also thanks for the data.

**Comment by gveres** [comment]
Hi @SahilJindal1 , you're welcome, I hope you'll find the corpus useful! As for the website, it's a defunct project by now unfortunately, no longer active, that's why the website isn't working. Maybe at some point in the future we'll revive it, but not in focus right now.
